Repository dcapal/dcapal, pull requests merged in 2023-11, with the labels that each got.

#141 33 suggest the minimum investment amount for reach the target allocation
  dcapal-frontend/package-lock.json
  dcapal-frontend/public/locales/en/translation.json
  dcapal-frontend/public/locales/it/translation.json
  dcapal-frontend/src/components/allocationFlow/investStep.js
  dcapal-frontend/src/workers/analyzer.js
  dcapal-optimizer-wasm/src/lib.rs
  dcapal-optimizer-wasm/src/optimize/advanced.rs
  dcapal-optimizer-wasm/src/optimize/mod.rs
  dcapal-optimizer-wasm/src/optimize/suggestions.rs
  dcapal-optimizer-wasm/tests/test_runner/main.rs
Labels: FE-enhancement, OPT-enhancement, hacktoberfest-accepted

#156 Refactor `portfolioReducer` store to support multiple portfolios
  .github/workflows/deploy.yml
  dcapal-backend/docker-compose.yml
  dcapal-frontend/demo/dcapal-60-40.json
  dcapal-frontend/demo/dcapal-all-seasons.json
  dcapal-frontend/demo/dcapal-mrrip.json
  dcapal-frontend/package-lock.json
  dcapal-frontend/package.json
  dcapal-frontend/public/locales/en/translation.json
  dcapal-frontend/public/locales/it/translation.json
  dcapal-frontend/src/app/index.js
  dcapal-frontend/src/app/store.js
  dcapal-frontend/src/components/allocationFlow/ccyStep/index.js
  dcapal-frontend/src/components/allocationFlow/endStep/allocateCard.js
  dcapal-frontend/src/components/allocationFlow/endStep/index.js
  dcapal-frontend/src/components/allocationFlow/importStep.js
  dcapal-frontend/src/components/allocationFlow/investStep.js
  dcapal-frontend/src/components/allocationFlow/portfolioStep/assetCard.js
  dcapal-frontend/src/components/allocationFlow/portfolioStep/index.js
  dcapal-frontend/src/components/allocationFlow/portfolioStep/portfolioSlice.js
  dcapal-frontend/src/components/allocationFlow/portfolioStep/searchBar.js
  dcapal-frontend/src/components/allocationFlow/portfolioStep/transactionFees.js
  dcapal-frontend/src/components/exportBtn.js
  dcapal-frontend/src/index.js
  dcapal-frontend/webpack.common.js
Labels: FE-enhancement

#177 Multiple portfolios UI
  README.md
  dcapal-frontend/demo/dcapal-hodlx.json
  dcapal-frontend/images/icons/close-menu.svg
  dcapal-frontend/images/icons/edit.svg
  dcapal-frontend/public/locales/en/translation.json
  dcapal-frontend/public/locales/it/translation.json
  dcapal-frontend/src/app/appSlice.js
  dcapal-frontend/src/app/config.js
  dcapal-frontend/src/app/index.js
  dcapal-frontend/src/app/providers.js
  dcapal-frontend/src/app/store.js
  dcapal-frontend/src/components/allocationFlow/index.js
  dcapal-frontend/src/components/allocationFlow/portfolioSlice.js
  dcapal-frontend/src/components/allocationFlow/steps/ccy/ccyGroup.js
  dcapal-frontend/src/components/allocationFlow/steps/ccy/ccyRadio.js
  dcapal-frontend/src/components/allocationFlow/steps/ccy/index.js
  dcapal-frontend/src/components/allocationFlow/steps/end/allocateCard.js
  dcapal-frontend/src/components/allocationFlow/steps/end/index.js
  dcapal-frontend/src/components/allocationFlow/steps/importFile.js
  dcapal-frontend/src/components/allocationFlow/steps/invest.js
  dcapal-frontend/src/components/allocationFlow/steps/portfolio/assetCard.js
  dcapal-frontend/src/components/allocationFlow/steps/portfolio/index.js
  dcapal-frontend/src/components/allocationFlow/steps/portfolio/searchBar.js
  dcapal-frontend/src/components/allocationFlow/steps/portfolio/transactionFees.js
  dcapal-frontend/src/components/allocationFlow/steps/portfolios/index.js
  dcapal-frontend/src/components/allocationFlow/steps/portfolios/portfolioCard.js
  dcapal-frontend/src/components/core/inputText.js
  dcapal-frontend/src/components/core/launchBtn.js
  dcapal-frontend/src/components/core/navBar.js
  dcapal-frontend/src/components/exportBtn.js
  dcapal-frontend/src/routes/demoPage.js
  dcapal-frontend/src/routes/router.js
  dcapal-frontend/src/style.css
Labels: FE-enhancement

#191 Fix `Solver` problems never deleted causing WASM memory leak
  Cargo.toml
  dcapal-frontend/package-lock.json
  dcapal-frontend/src/workers/analyzer.js
  dcapal-frontend/src/workers/solver.js
  dcapal-optimizer-wasm/src/lib.rs
Labels: OPT-bug

#192 Refresh Prometheus visitors stats at startup
  dcapal-backend/src/lib.rs
  dcapal-backend/src/repository/mod.rs
Labels: BE-enhancement
